app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

app/main/routes.py
from flask import render_template, request, Blueprint
from app.models import Post



main = Blueprint('main', __name__)

from app import create_app
app = create_app()
app.app_context().push()


@main.route("/")
@main.route("/home/")
def home():
    return render_template("home.html", title="home")


@main.route("/about/")
def about():
    return render_template("about.html", title="about")


@main.route("/services/")
def services():
    return render_template("services.html", title="services")


@main.route("/blog/")
def blog():
    page = request.args.get('page', 1 , type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=4)
    return render_template("blog.html", title="blogposts",posts=posts)


@main.route("/team/")
def team():
    return render_template("team.html", title="team members")

app/posts/routes.py
from flask import url_for, render_template, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from app import db
from app.models import Post
from app.posts.forms import PostForm 


posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET','POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template("create_post.html", title="New post",
                            form=form, legend='New Post')


@posts.route("/post/<int:post_id>/")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update/", methods=['GET','POST'])
@login_required
def updatepost(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated successfully', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data= post.content
    return render_template("create_post.html", title="Update post",
                            form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete/", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted successfully', 'success')
    return redirect(url_for('main.home'))

app/users/routes.py
from flask import url_for, render_template, flash, redirect, request, abort, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from app import db , bcrypt
from app.models import User, Post
from app.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                        RequestResetForm, ResetPasswordForm)
from app.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register/", methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
        #so that the user can't login more than once after first login 
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username= form.username.data, email=form.email.data,password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Account created successfully,you can now log in', 'success')
        return redirect(url_for('users.login'))
    return render_template("register.html", title="Register", form = form)


@users.route("/login/", methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash(f'Logged in {user.username} successfully', 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
            #redirect to next page if next page exists else redirect to home page
        else:
            flash('Login was unsuccessful. Please check email and password', 'danger')
    return render_template("login.html", title="Login", form = form)


@users.route('/logout/')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/profile/', methods=['GET','POST'])
@login_required
def profile():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file= picture_file
        current_user.username= form.username.data
        current_user.email= form.email.data
        db.session.commit()
        flash('your account has been updated!', 'success')
        return redirect(url_for('users.profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_photo/' + current_user.image_file)
    return render_template("profile.html", title="Profile",
                            image_file=image_file, form=form)


@users.route("/user/<string:username>/")
def user_posts(username):
    page = request.args.get('page', 1 , type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
            .order_by(Post.date_posted.desc())\
            .paginate(page=page, per_page=4)
    return render_template("user_posts.html", user=user, title="blogposts", posts=posts)


@users.route("/reset_password/", methods=['GET','POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.','info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET','POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Password was updated successfully', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

app/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <header>
        <a href="" class="logo"><img src="{{ url_for('static',filename = 'css/img/io.png' ) }}" alt=""></a>
        <div id="toggle" onclick="toggle()"></div>
    </header>
    <div class="about-content">
        <h1>THE ABOUT </h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus, minus veritatis fugit eum in dolorem aliquid
            praesentium dolorum veniam facere ipsum, odit, ipsam tempora impedit? Alias molestiae quasi illo laboriosam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus, minus veritatis fugit eum in dolorem aliquid
            praesentium dolorum veniam facere ipsum, odit, ipsam tempora impedit? Alias molestiae quasi illo laboriosam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus, minus veritatis fugit eum in dolorem aliquid
            praesentium dolorum veniam facere ipsum, odit, ipsam tempora impedit? Alias molestiae quasi illo laboriosam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus, minus veritatis fugit eum in dolorem aliquid
            praesentium dolorum veniam facere ipsum, odit, ipsam tempora impedit? Alias molestiae quasi illo laboriosam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus, minus veritatis fugit eum in dolorem aliquid
            praesentium dolorum veniam facere ipsum, odit, ipsam tempora impedit? Alias molestiae quasi illo laboriosam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus, minus veritatis fugit eum in dolorem aliquid
            praesentium dolorum veniam facere ipsum, odit, ipsam tempora impedit?.</p>
    </div>
    
{% endblock content %}

app/templates/blog.html
{% extends "layout.html" %}
{% block content %}
    <header>
        <a href="" class="logo"><img src="{{ url_for('static',filename = 'css/img/io.png' ) }}" alt=""></a>
        <div id="toggle" onclick="toggle()"></div>
    </header>
    <div class="about-content">
    <h3 class="m-15">RECENT POSTS</h3>
    {% for post in posts.items %}
        <article class="media content-section">
          <img src="{{ url_for('static', filename='profile_photo/' + post.author.image_file) }}" class="rounded-circle" width="120px" height="120px" alt="user-image">
          <div class="media-body">
            <div class="article-metadata">
              <a href="{{ url_for('users.user_posts', username=post.author.username) }}"><p class="mr-2 ml-2">{{ post.author.username }}</p></a>
              <small class="text-muted ml-2">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h4><a class="article-title ml-2" href="{{ url_for('posts.post', post_id = post.id) }}">{{ post.title }}</a></h4>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    <div class="page-buttons">
      {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if page_num %}
            {% if posts.page == page_num %}
              <a class="btn btn-info mb-4 ml-1 mr-1" href="{{ url_for('main.blog', page=page_num) }}">{{ page_num }}</a>
            {% else %}
              <a class="btn btn-outline-info mb-4 ml-1 mr-1" href="{{ url_for('main.blog', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
          {% else %}
            ...
          {% endif %}
        {% endfor %}
    </div>
        
{% endblock content %}

app/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
    <header>
        <a href="" class="logo"><img src="{{ url_for('static',filename = 'css/img/io.png' ) }}" alt=""></a>
        <div id="toggle" onclick="toggle()"></div>
    </header>
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag()}}
            <fieldset class="form-group">
                <h1 class="border-bottom mb-4">{{ legend }}</h1>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                        <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                        <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info mt-2") }}
            </div>
        </form>
    </div>
{% endblock content %}

app/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <header>
        <a href="" class="logo"><img src="{{ url_for('static',filename = 'css/img/io.png' ) }}" alt=""></a>
        <div id="toggle" onclick="toggle()"></div>
    </header>
    <div class="content">
        <h2>Good Day, <br>I'm <span>Ezihe Godswill</span></h2>
        <p>FULL-STACK WEB DEVELOPER | PYTHON DEVELOPER | BLOCKCHAIN ENTHUSIAST | PHARMACY STUDENT</p>
        <a href="">know more</a>
    </div>

{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <!--Bootstrap css-->
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/all.css') }}">
    <!--Custom css-->
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/main.css') }}">
    {% if title %}
        <title>Cone Blog - {{ title }}</title>
    {% else %}
        <title>Cone Blog</title>
    {% endif %}
</head>
<body>
    <section class="banner" id="sec">
        <div class="extension">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}
            {% endblock %}
        </div>
        
        <ul class="iconics">
            <li><a href="/"><i class="fab fa-facebook"></i></a></li>
            <li><a href=""><i class="fab fa-twitter"></i></a></li>
            <li><a href=""><i class="fab fa-github"></i></a></li>
            <li><a href=""><i class="fab fa-instagram"></i></a></li>
            <li><a href=""><i class="fab fa-linkedin"></i></a></li>
        </ul>
    </section>
    <div id="navigation">
        <ul>
            <li><a href="{{ url_for('main.home') }}">Home</a></li>
            <li><a href="{{ url_for('main.about') }}">About</a></li>
            <li><a href="{{ url_for('main.services') }}">Services</a></li>
            <li><a href="{{ url_for('main.blog') }}">Blog</a></li>
            <li><a href="{{ url_for('main.team') }}">Team</a></li>

            {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('posts.new_post') }}">New Posts</a></li>
                <li><a href="{{ url_for('users.profile') }}">Profile</a></li>
                <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
            {% else %}
                <li><a href="{{ url_for('users.login') }}">Login</a></li>
                <li><a href="{{ url_for('users.register') }}">register</a></li>
            {% endif %}
        </ul>
    </div>
    
    
    <footer></footer>


    <script type="text/javascript">
    function toggle(){
        var sec = document.getElementById('sec');
        var nav = document.getElementById('navigation');
        sec.classList.toggle('active');
        nav.classList.toggle('active');
    }
    jQuery.htmlPrefilter = function( html ) {
	return html;
};
    </script>

    <!--Bootstrap javascript-->
    <script src="{{ url_for('static', filename = 'js/popper.min.js') }}"></script>
    <script src="https://code.jquery.com/jquery-3.5.0.slim.min.js"></script>
    <script src="{{ url_for('static', filename = 'js/all.js') }}"></script>
    <script src="{{ url_for('static', filename = 'js/bootstrap.min.js') }}"></script>
    
</body>
</html>

app/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <header>
        <a href="" class="logo"><img src="{{ url_for('static',filename = 'css/img/io.png' ) }}" alt=""></a>
        <div id="toggle" onclick="toggle()"></div>
    </header>
    <div class="about-content">
        <h1>LOGIN</h1>
    </div>
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag()}}
            <fieldset class="form-group">
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span class="text-danger">{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span class="text-danger">{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                            {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info mt-2") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Don't have an account?<a href="{{ url_for('users.register') }}" class="ml-2">Sign Up</a>
        </small>
    </div>
        
{% endblock content %}

app/templates/post.html
{% extends "layout.html" %}
{% block content %}
    <header>
        <a href="" class="logo"><img src="{{ url_for('static',filename = 'css/img/io.png' ) }}" alt=""></a>
        <div id="toggle" onclick="toggle()"></div>
    </header>
    <div class="about-content">
    <h3 class="m-15">POST</h3>
        <article class="media content-section">
          <img src="{{ url_for('static', filename='profile_photo/' + post.author.image_file) }}" class="rounded-circle article-image" width="120px" height="120px" alt="user_image">
          <div class="media-body">
            <div class="article-metadata">
              <a href="{{ url_for('users.user_posts', username=post.author.username) }}"><p class="mr-2 ml-2">{{ post.author.username }}</p></a>
              <small class="text-muted ml-2">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
              {% if post.author == current_user %}
                <div>
                    <a href="{{ url_for('posts.updatepost', post_id= post.id) }}" class="btn btn-secondary btn-sm m-1 ml-2">Update</a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-backdrop="static" data-target="#deleteModalCenter">Delete</button>
                </div>
              {% endif %}
            </div>
            <h4 class="article-title">{{ post.title }}</h4>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
        <!--Modal block-->
        <div class="modal fade" id="deleteModalCenter" tabindex="-1" role="dialog" data-backdrop="false" aria-labelledby="deleteModalLabel" aria-hidden="true" >
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h3 class="modal-title" id="deleteModalLongTitle">Delete Post</h3>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>This procedure is an irreversible one. If you delete this post you can't reverse it.Are you sure you want to go ahead?</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" type="button" data-dismiss="modal">Close</button>
              <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
              </form>
              </div>
            </div>
          </div>
        </div>
{% endblock content %}

app/templates/profile.html
{% extends "layout.html" %}
{% block content %}
    <header>
        <a href="" class="logo"><img src="{{ url_for('static',filename = 'css/img/io.png' ) }}" alt=""></a>
        <div id="toggle" onclick="toggle()"></div>
    </header>
    <div class="about-content">
        <h1>Your Profile</h1>
        <div class="content-section">
            <div class="media">
                <img src="{{ image_file }}" alt="" class="rounded-circle account-img">
            </div>
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
    
        <!--FORM FOR PROFILE from register.html-->
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group-field">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                        <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.picture.label()}}
                {{ form.picture(class="form-control-file")}}
                {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                <span class="text-danger">{{ error }}</span><br>
                {% endfor %}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>


    </div>
{% endblock content %}

app/templates/register.html
{% extends "layout.html" %}
{% block content%}
    <header>
        <a href="" class="logo"><img src="{{ url_for('static',filename = 'css/img/io.png' ) }}" alt=""></a>
        <div id="toggle" onclick="toggle()"></div>
    </header>
    <div class="about-content">
        <h1>JOIN TODAY</h1>
    </div>
    <div class="content-section">
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group-field">
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span class="text-danger">{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                            {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span class="text-danger">{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span class="text-danger">{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                            {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span class="text-danger">{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                            {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already have an account?<a class="ml-2" href="{{ url_for('users.login') }}" class="ml-2">Sign In</a>
        </small>
    </div>
{% endblock content %}

app/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <header>
        <a href="" class="logo"><img src="{{ url_for('static',filename = 'css/img/io.png' ) }}" alt=""></a>
        <div id="toggle" onclick="toggle()"></div>
    </header>
    <div class="about-content">
    <h3 class="m-15">Posts by {{ user.username }} ({{ posts.total }}) </h3>
    {% for post in posts.items %}
        <article class="media content-section">
          <img src="{{ url_for('static', filename='profile_photo/' + post.author.image_file) }}" class="rounded-circle" alt="{{ user.username }}">
          <div class="media-body">
            <div class="article-metadata">
              <a href="{{ url_for('users.user_posts', username=post.author.username) }}"><p class="mr-2 ml-2">{{ post.author.username }}</p></a>
              <small class="text-muted ml-2">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h4><a class="article-title ml-2" href="{{ url_for('posts.post', post_id = post.id) }}">{{ post.title }}</a></h4>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    <div class="page-buttons">
      {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if page_num %}
            {% if posts.page == page_num %}
              <a class="btn btn-info mb-4 ml-1 mr-1" href="{{ url_for('users.user_posts',username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% else %}
              <a class="btn btn-outline-info mb-4 ml-1 mr-1" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% endif %}
          {% else %}
            ...
          {% endif %}
        {% endfor %}
    </div>
        
{% endblock content %}